### ISSUE TITLE
Comparação de forma responsiva

### ISSUE THREAD

**Issue by mfurquim** [mfurquim/eLugar#15]
Eu, como usuário, gostaria de visualizar a tela de comparação de forma responsiva, para utilizar o site em vários dispositivos.

**Comment by educastro** [comment]
Ao invés de fazer a comparação vamos fazer a história algo como "Eu, como usuário, gostaria que o eLugar fosse responsivo, para que eu pudesse utilizar o serviço em diversos dispositivos"?
