### ISSUE TITLE
Mudar o efeito de hover das cidades

### ISSUE THREAD

**Issue by felipe72** [mfurquim/eLugar#16]
User Story 6
Eu, como usuário, gostaria de ​passar o mouse por cima de determinada cidade e receber um feedback melhor​, para facilitar a compreensão.

**Comment by educastro** [comment]
**Critério de Aceitação**: ao passar o mouse sobre uma determinada cidade o usuário deve visualizar alguns dos atributos de maior interesse da mesma sem a necessidade de abrir a página.

**Cenários**

**Dado** Estou na página de listagem e visualização de cidades
**Quando** posiciono o cursor do mouse sob a cidade
**Então** uma nova camada exibe os atributos de maior interesse na cidade
