### ISSUE TITLE
Atributos em contexto nacional

### ISSUE THREAD

**Issue by mfurquim** [mfurquim/eLugar#17]
Eu, como usuário, gostaria de visualizar graficamente os três melhores atributos em contexto nacional quando visualizar uma cidade, para ajudar-me a escolher a melhor cidade.

**Comment by educastro** [comment]
Qual a diferença dessa issue para #3 ?

**Comment by mfurquim** [comment]
A ideia dessa _feature_ é colocar um indicador nos atributos Top 3 nacionalmente. Se brasília tem o melhor IDH do Brasil, então deve aparecer uma medalha de ouro (ou algo assim) na cartinha do IDH. Aquela cidade que tiver o segundo melhor IDH deve ficar com uma medalha de prata, e a mesma coisa é feita para o terceiro melhor IDH. Isso deve ser feito para todos os atributos.

**Comment by educastro** [comment]
Mas a #3 não é a mesma coisa?

**Comment by mateus-andrade** [comment]
A #3 é um ranking completo por atributo, essa são indicadores na visualização dos atributos das cidades se ela está entre as 3 melhores naquele atributo no contexto nacional
