### ISSUE TITLE
Login do usuário

### ISSUE THREAD

**Issue by mfurquim** [mfurquim/eLugar#2]
Eu como usuário quero realizar login utilizando minha conta do Facebook para que eu possa usufruir de mais features do sistema

**Comment by educastro** [comment]
**Critério de Aceitação**: poder criar uma conta no eLugar sem a necessidade de preencher um formulário de cadastro, apenas fornecendo autorização por meio do Facebook para que os dados de um determinado usuário sejam extraídos

**Cenários**

**Dado** estou no eLugar
**Quando** clico no botão "Cadastro" e em seguida no botão "Criar com o Facebook"
**Então** Estou logado no eLugar

**Dado** estou no eLugar
**Quando** clico no botão "Login" e em seguida no botão "Login com o Facebook"
**Então** Estou logado no eLugar
