### ISSUE TITLE
Gerar relatórios

### ISSUE THREAD

**Issue by mfurquim** [mfurquim/eLugar#21]
Eu, como usuário, gostaria de gerar relatórios sobre determinada cidade ou comparação entre cidades, para facilitar a visualização da informação.

- Relatório estará disponível para download em PDF

**Comment by educastro** [comment]
**Critério de Aceitação**: ao estar na página de uma determinada cidade usuário deve poder obter um relatório sobre a mesma, iniciar uma comparação com outra cidade ou exportar um relatório em PDF.

**Cenários**

**Dado** estou no eLugar e clico no botão "VER CIDADES"
**Quando** clico em uma determinada cidade em exibição na lista
**Então** estou em uma nova página contendo um relatório sobre essa cidade

**Dado** estou na página de uma determinada cidade contendo seu relatório no eLugar
**Quando** clico no botão "Exportar"
**Então** realizo o download de um arquivo PDF com as informações contidas no relatório

**Dado** estou na página de uma determinada cidade contendo seu relatório no eLugar
**Quando** clico no botão "Compare"
**Então** estou em uma nova página com uma lista de cidades que posso realizar a comparação com a cidade inicial

**Dado** estou na página com uma lista com todas as cidades que posso realizar a comparação com a cidade inicial
**Quando** clico em uma determinada cidade
**Então** estou em uma nova página com um relatório comparativo entre as duas cidades, a inicial e a recém-escolhida

**Dado** estou na página com um relatório comparativo entre duas determinadas cidades 
**Quando** clico no botão "Exportar"
**Então** realizo o download de um arquivo PDF com as informações contidas no relatório

**Dado** estou na página com um relatório comparativo entre duas determinadas cidades 
**Quando** clico no botão "Voltar"
**Então** estou novamente na página em que posso escolher uma nova cidade para realizar uma nova comparação com a cidade inicial
