### ISSUE TITLE
Ranking dos atributos

### ISSUE THREAD

**Issue by mfurquim** [mfurquim/eLugar#3]
Eu como usuário quero visualizar de forma clara se um atriubto de determinada cidade é um dos Top 3 do país, para facilitar a visualização das melhores cidades.

**Comment by educastro** [comment]
**Critério de Aceitação**: ao visualizar o relatório de uma determinada cidade o usuário deve ser capaz de identificar quais atributos estão entre os de maior destaque no país, se houver algum.

**Cenários**

**Dado** Estou na página de uma determinada cidade
**Quando** visualizo o relatório com todos os atributos da cidade e algum deles possui o melhor indicador do Brasil
**Então** uma medalha de ouro deve estar ao lado do atributo para que eu saiba que é o melhor

**Dado** Estou na página de uma determinada cidade
**Quando** visualizo o relatório com todos os atributos da cidade e algum deles possui o segundo melhor indicador do Brasil
**Então** uma medalha de prata deve estar ao lado do atributo para que eu saiba que é o segundo melhor

**Dado** Estou na página de uma determinada cidade
**Quando** visualizo o relatório com todos os atributos da cidade e algum deles possui o terceiro indicador do Brasil
**Então** uma medalha de bronze deve estar ao lado do atributo para que eu saiba que é o treceiro melhor
